# Generated by Django 2.2.1 on 2019-05-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_remove_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='detail',
            field=models.TextField(default=''),
        ),
    ]
